# Generated by Django 5.1.1 on 2024-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_room_description_room_image_alter_room_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
    ]
